spring:
  application:
    name: healthy_meal_backend
  config:
    import: classpath:application-secret.yml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  grpc:
    server:
      max-inbound-message-size: 20971520
  autoconfigure:
    exclude: net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration

springdoc:
  swagger-ui:
    path: swagger-ui

server:
  port: 51820

logging:
  level:
    root: info
